### ISSUE TITLE
Please analyse and select Dataset!

### ISSUE THREAD

**Issue by urmi6899** [shantanu109/calorieApp_server#1]
Very limited dataset: 
https://www.kaggle.com/kerneler/starter-food-and-their-calories-34890bb0-f

**Comment by urmi6899** [comment]
Potential dataset:
https://data.world/adamhelsinger/food-nutrition-information/workspace/intro

**Comment by Sahil-Nande** [comment]
Merged and cleaned the dataset. Uploaded in food_data directory.
