### ISSUE TITLE
Importing Dataset into mongoDB

### ISSUE THREAD

**Issue by gargvarun250** [shantanu109/calorieApp_server#3]
Please check the below link and let me know if this helps:
https://docs.mongodb.com/guides/server/import/

**Comment by leanneserrao** [comment]
Please check the below link as well
https://kb.objectrocket.com/mongo-db/how-to-import-a-csv-into-mongodb-327
It shows how to import a csv into MongoDB.

**Comment by Sahil-Nande** [comment]
Imported CSV dataset into MongoDB.
